### PR TITLE
Rarities 2.0

### PR DESCRIPTION
**Pull request by funkychicken493**

### CODE REVIEW

**Comment by funkychicken493** [comment]
@Ph4i1ur3

**Review by Eutherin — CHANGES_REQUESTED** [review]
this causes ghastly to not work correctly.
image

**Comment by funkychicken493** [comment]
removed my changes, idk how to do particles in denizen

**Comment by funkychicken493** [comment]
@Eutherin review pls, not doing ghastly

**Review by Eutherin — APPROVED** [review]

**Pull request merged**
